feat (#19): Get current user session
timemates/sdk pull request #26
Opened 2023-07-10 12:15 UTC by y9slavabogu

2023-07-12 19:46 UTC, y9slavabogu commented
open#19

2023-07-12 20:16 UTC, y9vad9 requested changes
you miss protofiles

2023-07-12 20:49 UTC, y9vad9 requested changes

2023-07-12 20:49 UTC, y9vad9 commented on grpc-engine/src/main/proto/io/timemates/api/timers/sessions/requests/GetUserSessionsRequest.proto
> +        Timer timer = 1;
add optional here:
`optional Timer timer = 1;`

2023-07-12 20:53 UTC, y9vad9 approved these changes

2023-07-12 21:40 UTC, y9vad9 requested changes

2023-07-12 21:40 UTC, y9vad9 commented on grpc-engine/src/main/proto/io/timemates/api/timers/sessions/TimerSessionsService.proto
> +  rpc getCurrentTimerSession(GetCurrentTimerSessionRequest) returns (Timer);
there should be google.protobuf.Empty

2023-07-13 09:23 UTC, sliderzxc reviewed
good job

2023-07-13 09:23 UTC, sliderzxc approved these changes

2023-07-13 14:55 UTC, merged